import os
import shutil
import tempfile
import structlog
import httpx
from git import Repo
from typing import Optional, Dict, Any
from core.config import settings

logger = structlog.get_logger()

class GitHubClient:
    """Handles GitHub interactions: cloning, patching, and PR creation."""
    
    def __init__(self, token: Optional[str] = None):
        self.token = token or settings.GITHUB_TOKEN
        self.api_base = "https://api.github.com"
        self.headers = {
            "Authorization": f"token {self.token}" if self.token else "",
            "Accept": "application/vnd.github.v3+json",
        }

    async def create_pr(self, repo_url: str, fix: Dict[str, Any], base_branch: str = "main") -> Dict[str, Any]:
        """
        Creates a PR for a specific fix.
        Logic: 
        1. Clone repo to temp dir
        2. Create feature branch
        3. Apply patch
        4. Push branch
        5. API call to open PR
        """
        if not self.token:
            raise ValueError("GitHub token is not configured. Automated PRs disabled.")

        # Extract owner/repo from URL
        # e.g. https://github.com/owner/repo
        parts = repo_url.rstrip("/").split("/")
        if len(parts) < 2:
            raise ValueError(f"Invalid repository URL: {repo_url}")
        owner_repo = f"{parts[-2]}/{parts[-1]}"
        
        temp_dir = tempfile.mkdtemp()
        try:
            # 1. Clone
            authed_url = repo_url.replace("https://", f"https://x-access-token:{self.token}@")
            repo = Repo.clone_from(authed_url, temp_dir)
            
            # 2. Branch
            branch_name = f"atlasstack/fix-{os.urandom(4).hex()}"
            new_branch = repo.create_head(branch_name)
            new_branch.checkout()
            
            # 3. Apply Patch
            file_path = os.path.join(temp_dir, fix["file_path"])
            if not os.path.exists(file_path):
                raise FileNotFoundError(f"File {fix['file_path']} not found in repository")
            
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()
            
            # Simple replacement logic (can be replaced with git apply if we have a diff)
            if fix.get("code_remove") and fix["code_remove"] in content:
                new_content = content.replace(fix["code_remove"], fix.get("code_add", ""))
            else:
                # If exact match fails, try a line-by-line strategy or just append if it's an addition
                # For Phase 1/2, we'll favor exact match or simple addition
                new_content = content + "\n" + fix.get("code_add", "") if not fix.get("code_remove") else content

            with open(file_path, "w", encoding="utf-8") as f:
                f.write(new_content)
            
            # 4. Commit and Push
            repo.index.add([fix["file_path"]])
            repo.index.commit(f"AtlasStack Fix: {fix['problem']}")
            
            origin = repo.remote(name="origin")
            origin.push(branch_name)
            
            # 5. Open PR via API
            pr_data = {
                "title": f"AtlasStack: Fix for {fix['problem']}",
                "body": (
                    f"### 🛡 Security fix suggested by AtlasStack\n\n"
                    f"**Problem:** {fix['problem']}\n"
                    f"**Remediation:** {fix.get('eli5_explanation', 'Automatic patch applied.')}\n\n"
                    f"This PR was automatically generated by AtlasStack AI."
                ),
                "head": branch_name,
                "base": base_branch
            }
            
            async with httpx.AsyncClient() as client:
                res = await client.post(
                    f"{self.api_base}/repos/{owner_repo}/pulls",
                    headers=self.headers,
                    json=pr_data
                )
                
                if res.status_code != 201:
                    logger.error("Failed to create PR", status=res.status_code, response=res.text)
                    raise Exception(f"GitHub API Error: {res.json().get('message', 'Unknown error')}")
                
                return res.json()
                
        finally:
            shutil.rmtree(temp_dir)

def get_github_client(token: Optional[str] = None) -> GitHubClient:
    return GitHubClient(token=token)
